apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-api
  template:
    metadata:
      labels:
        app: hackathon-api
    spec:
      containers:
        - name: hackathon-api
          image: jivaofficial/hackathon-api:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-api-service
spec:
  selector:
    app: hackathon-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
