apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - 139.59.6.252.nip.io
      secretName: hackathon-tls
  rules:
    - host: 139.59.6.252.nip.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hackathon-api-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hackathon-ui-service
                port:
                  number: 80
